#!/bin/bash

prefix="/usr/local"
www_directory="/var/www/streaming"
novnc_directory="/usr/share/novnc"
channels=$(seq 6)

lib_directory="$prefix/lib"
sbin_directory="$prefix/sbin"
etc_directory="$prefix/etc"
var_spool_directory="$prefix/var/spool"

cgi_bin_directory="$www_directory/cgi-bin"

install="install -C -v"

install_symlink ()
{
  if cmp -s "$1" "$2"; then
    true
  else
    echo -n "symlink: "
    ln -svf "$1" "$2"
  fi
}

install_directory ()
{
  if [ -d "$1" ]; then
    true
  else
    echo -n "directory: "
    mkdir -v "$1"
  fi
  chown "$2" "$1"
  chmod "$3" "$1"
}

echo "Installing PULT ..."

for file in \
  novnc \
  vncrepeater \
  vncserver \
  cvh-camera \
  cvh-camera-update-credentials
do
  $install -o root -g root -m 755 "sbin/$file" "$sbin_directory/"
done

$install -o root -g root -m 644 sbin/*.{py,js} "$sbin_directory/"
$install -o root -g root -m 755 lib/pult/*.{module,daemon} "$lib_directory/pult/"
$install -o root -g root -m 644 lib/pult/*.{py,functions} "$lib_directory/pult/"
install_symlink "$lib_directory/pult/pult.daemon" "$sbin_directory/pultd"
$install -o root -g root -m 644 etc/pult/* "$etc_directory/pult/"
$install -o root -g root -m 644 etc/pult/* "$etc_directory/pult/"

for file in pult pult-upload; do
  $install -o root -g root -m 755 var/www/site/cgi-bin/"$file".cgi "$cgi_bin_directory/"
  (
    cd "$cgi_bin_directory"
    for c in $channels; do
      install_symlink "$file".cgi "$file-$c".cgi
    done
  )
done

$install -o root -g root -m 644 var/www/site/pult/*.png "$www_directory/pult/"
$install -o root -g root -m 644 var/www/site/pult/stylesheets/default.css "$www_directory/pult/stylesheets/"
$install -o root -g root -m 644 var/www/site/cvh-camera/* "$www_directory/cvh-camera/"
$install -o root -g root -m 644 novnc/vnc.html "$novnc_directory/"
$install -o root -g root -m 644 novnc/core/*.js "$novnc_directory/core/"
$install -o root -g root -m 644 novnc/app/*.js "$novnc_directory/app/"
$install -o root -g root -m 644 novnc/app/styles/*.css "$novnc_directory/app/styles/"
$install -o root -g root -m 644 etc/systemd/system/* /etc/systemd/system/

install_directory "$www_directory/pult-upload" www-data.pult 6575
install_directory "$var_spool_directory/pult" www-data.pult 6775

cat << EOF
... done.

Please install manually:
 - etc/nginx/sites-available/fragment.conf  in your nginx configuration
 - etc/janus/janus.plugin.videoroom.jcfg.fragment  in your janus configuration
 - var/www/site/vnc  as your VNC channel web page
 - adapt cvh-camera-update-credentials to your www directory,
   and add a cron job to execute it periodically, for instance:
   */15 * * * * $sbin_directory/cvh-camera-update-credentials
 - activate and enable the services in /etc/systemd/system
EOF
