#!/bin/sh

www_dir="/var/www/streaming/cvh-camera"
novnc_dir="/usr/share/novnc/app"
calculator="/usr/local/sbin/coturn-get-credentials.py"
secret=$(cat "/etc/turnserver.conf" | grep "static-auth-secret" | sed -e 's/^.*= *//')

user="cvh-camera"
in_file_receiver="$www_dir/camera-receiver.js.in"
out_file_receiver="$www_dir/camera-receiver.js"
in_file_sender="$www_dir/camera-sender.js.in"
out_file_sender="$www_dir/camera-sender.js"
in_file_novnc="$novnc_dir/camera-receiver.js.in"
out_file_novnc="$novnc_dir/camera-receiver.js"
warning_file="$www_dir/warning.js.in"

credentials=$(/usr/bin/python2 "$calculator" "$user" "$secret")
turn_user=$(echo "$credentials" | cut -d " " -f 1)
turn_password=$(echo "$credentials" | cut -d " " -f 2)

cat "$warning_file" "$in_file_receiver" | sed -e "s,@TURN_USER@,$turn_user,g" -e "s,@TURN_PASSWORD@,$turn_password,g" > "$out_file_receiver"
cat "$warning_file" "$in_file_sender" | sed -e "s,@TURN_USER@,$turn_user,g" -e "s,@TURN_PASSWORD@,$turn_password,g" > "$out_file_sender"
cat "$warning_file" "$in_file_novnc" | sed -e "s,@TURN_USER@,$turn_user,g" -e "s,@TURN_PASSWORD@,$turn_password,g" > "$out_file_novnc"
